name: Production Portal Deployment

on:
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies production dependencies
        run: npm install --omit=dev

      - name: Build
        run: npm run build

      - name: Deploy
        if: success()
        run: echo "Uploading files to s3 in bucket"
